### ISSUE TITLE
1차 QA 이후 TODO

### ISSUE THREAD

**Issue by SeolJaeHyeok** [wanted-pre-onboarding-4/Movie#14]
## Search Page
- [x]  스타일 디테일 수정
- [x] 포스터 없는 경우 대체 이미지

## Detail Page 
- [x] 별점 수정
- [x]  별 색깔 수정
- [x] emotion 삭제
- [x] 태그 길이 수정
- [x] 포스터 이미지 없는 경우 핸들링
- [x] 중복되는 컴포넌트 분리
- [x] `async await` 지우기
- [x] 상세 페이지 진입 시 영상 자동 재생

## Movie Page
- [x] 카드 컴포넌트 스타일 통일
- [x] 인피니티 스크롤 구현 방법 통일
- [x] 공통 컴포넌트 정의 후 통일

## 기타
- [x] Suspense로 Loading Spinner 적용
- [x] 헤더 스타일 디테일 수정
- [x] 이미지 없는 경우 보여줄 대체 이미지 컴포넌트 만들기
- [x] `/` -> `/movie/popular`로 리다이렉트
- [x] 404 페이지 작업
